<?php
/**
 * Build markdown files for the ai-handoff/ file bridge (ChatGPT ↔ Cursor).
 *
 * @package ReactWoo_Flow
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Converts Flow handoff context into ai-handoff markdown files.
 */
class RWF_Handoff_Markdown {

	/**
	 * Template filenames shipped in the repo ai-handoff/ directory.
	 *
	 * @return string[]
	 */
	public static function template_filenames() {
		return array(
			'README.md',
			'current-task.md',
			'cursor-output.md',
			'test-output.md',
			'known-issues.md',
			'decisions.md',
		);
	}

	/**
	 * Build ai-handoff file map for an item (filename => markdown body).
	 *
	 * @param int $post_id Item post ID.
	 * @return array<string, string>
	 */
	public static function build_files_for_item( $post_id ) {
		$repo_root = dirname( RWF_PLUGIN_DIR );
		$files     = array();

		foreach ( self::template_filenames() as $filename ) {
			$path = $repo_root . '/ai-handoff/' . $filename;

			if ( is_readable( $path ) ) {
				$files[ $filename ] = (string) file_get_contents( $path );
			}
		}

		$files['current-task.md'] = self::build_current_task_markdown( $post_id );

		return $files;
	}

	/**
	 * Build current-task.md from a prepared development handoff.
	 *
	 * @param int $post_id Item post ID.
	 * @return string
	 */
	public static function build_current_task_markdown( $post_id ) {
		$context = RWF_AI::build_development_handoff_context( $post_id );
		$item    = isset( $context['item'] ) && is_array( $context['item'] ) ? $context['item'] : array();
		$title   = isset( $item['title'] ) ? (string) $item['title'] : '';
		$desc    = isset( $item['description'] ) ? (string) $item['description'] : '';

		$problem    = self::agent_value( $context, 'problem_statement' );
		$summary    = self::agent_value( $context, 'ai_summary' );
		$acceptance = self::agent_list( $context, 'acceptance_criteria' );
		$branch     = self::nested_string( $context, array( 'suggested_execution', 'branch' ) );
		$qa         = self::nested_string( $context, array( 'suggested_execution', 'qa_checklist' ) );
		$notes      = self::nested_string( $context, array( 'suggested_execution', 'developer_notes' ) );
		$spec       = isset( $context['specification'] ) ? trim( (string) $context['specification'] ) : '';

		$lines   = array();
		$lines[] = '# Current task';
		$lines[] = '';
		$lines[] = '> Generated by ReactWoo Flow item #' . (int) $post_id . ( $title ? ': ' . $title : '' ) . '.';
		$lines[] = '';
		$lines[] = '## Problem';
		$lines[] = '';
		$lines[] = $problem ? $problem : ( $summary ? $summary : ( $desc ? $desc : '_Fill in from triage if empty._' ) );
		$lines[] = '';
		$lines[] = '## Expected';
		$lines[] = '';
		$lines[] = $summary && $problem && $summary !== $problem ? $summary : '_See specification and acceptance test._';
		$lines[] = '';
		$lines[] = '## Actual';
		$lines[] = '';
		$lines[] = $desc && ( ! $problem || $desc !== $problem ) ? $desc : '_Describe current broken behaviour._';
		$lines[] = '';
		$lines[] = '## Files involved';
		$lines[] = '';
		$lines[] = '- ';

		$lines[] = '';
		$lines[] = '## What we already tried';
		$lines[] = '';
		$lines[] = '- _(Check ai-handoff/known-issues.md before editing.)_';
		$lines[] = '';
		$lines[] = '## Error / log';
		$lines[] = '';
		$lines[] = '```';
		$lines[] = '(paste from environment or support ticket)';
		$lines[] = '```';
		$lines[] = '';
		$lines[] = '## Acceptance test';
		$lines[] = '';

		if ( ! empty( $acceptance ) ) {
			foreach ( $acceptance as $criterion ) {
				$lines[] = '- [ ] ' . $criterion;
			}
		} else {
			$lines[] = '- [ ] ';
		}

		if ( $qa ) {
			$lines[] = '';
			$lines[] = '### QA checklist (from Flow)';
			$lines[] = '';
			$lines[] = $qa;
		}

		$lines[] = '';
		$lines[] = '## Do not touch';
		$lines[] = '';
		$lines[] = '- Unrelated plugins and release tooling unless listed in specification.';
		$lines[] = '';
		$lines[] = '## Specification';
		$lines[] = '';

		if ( $spec ) {
			$lines[] = $spec;
		} else {
			$lines[] = '_No specification markdown on this item yet._';
		}

		if ( $branch ) {
			$lines[] = '';
			$lines[] = '## Suggested branch';
			$lines[] = '';
			$lines[] = '`' . $branch . '`';
		}

		if ( $notes ) {
			$lines[] = '';
			$lines[] = '## Developer notes';
			$lines[] = '';
			$lines[] = $notes;
		}

		$lines[] = '';
		$lines[] = '## Cursor instructions';
		$lines[] = '';
		$lines[] = '1. Read `ai-handoff/known-issues.md` before editing.';
		$lines[] = '2. Find root cause before patching symptoms.';
		$lines[] = '3. Change only what this task requires.';
		$lines[] = '4. Run the smallest validation that matches **Acceptance test**.';
		$lines[] = '5. Update `ai-handoff/cursor-output.md` when finished (required).';
		$lines[] = '';

		return implode( "\n", $lines );
	}

	/**
	 * Read a string agent_analysis field from handoff context.
	 *
	 * @param array  $context Handoff context.
	 * @param string $key     Meta field key.
	 * @return string
	 */
	private static function agent_value( $context, $key ) {
		if ( empty( $context['agent_analysis'][ $key ]['value'] ) ) {
			return '';
		}

		return trim( (string) $context['agent_analysis'][ $key ]['value'] );
	}

	/**
	 * Read a list agent field (JSON array or newline-separated).
	 *
	 * @param array  $context Handoff context.
	 * @param string $key     Meta field key.
	 * @return string[]
	 */
	private static function agent_list( $context, $key ) {
		$raw = self::agent_value( $context, $key );

		if ( '' === $raw ) {
			return array();
		}

		$decoded = json_decode( $raw, true );

		if ( is_array( $decoded ) ) {
			return array_values(
				array_filter(
					array_map(
						static function ( $item ) {
							return trim( (string) $item );
						},
						$decoded
					)
				)
			);
		}

		$lines = preg_split( '/\r\n|\r|\n/', $raw );

		if ( ! is_array( $lines ) ) {
			return array( $raw );
		}

		return array_values(
			array_filter(
				array_map(
					static function ( $line ) {
						return trim( (string) $line );
					},
					$lines
				)
			)
		);
	}

	/**
	 * Safely read a nested string from context array.
	 *
	 * @param array $context Context.
	 * @param array $path    Key path.
	 * @return string
	 */
	private static function nested_string( $context, $path ) {
		$node = $context;

		foreach ( $path as $segment ) {
			if ( ! is_array( $node ) || ! array_key_exists( $segment, $node ) ) {
				return '';
			}

			$node = $node[ $segment ];
		}

		return trim( (string) $node );
	}
}
